openapi: 3.0.3
info:
  title: Tea API
  description: API for fetching a list of teas.
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /tea:
    get:
      summary: Get a list of teas
      operationId: getTeaList
      responses:
        '200':
          description: A list of teas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tea'

components:
  schemas:
    Tea:
      type: object
      properties:
        name:
          type: string
          example: "Earl Grey"

